### ISSUE TITLE
cvit function in 'demo_stan_arsenic.m'

### ISSUE THREAD

**Issue by vincentvalton** [avehtari/PSIS#2]
Hi,

I am trying to run the k-fold-CV example available in the 'demo_stan_arsenic' script, but I can't seem to be able to find the function 'cvit'.

Would it be possible to upload 'cvit' to the PSIS/m/ directory?

Best regards,

**Comment by vincentvalton** [comment]
Found a copy of the cvit.m function in GPstuff :)

Posting it here in case anyone else ends-up looking for it:
https://github.com/gpstuff-dev/gpstuff/blob/master/misc/cvit.m

Best regards,

**Comment by avehtari** [comment]
I'm sorry, I didn't notice this until now! I added the missing cvit.m
