### ISSUE TITLE
Translating the PSIS_LOO to Julia

### ISSUE THREAD

**Issue by alvaro1101** [avehtari/PSIS#3]
Hello:

I'm translating, mostly done, the matlab code of PSIS_LOO to Julia. I don't know if I should ask you to merge it here (if it's possible) or try to merge it in [Stan.jl](https://github.com/goedman/Stan.jl)( This option has the license problem (This is GPL code and Stan.jl has a MIT license, so I don't know  exactly this works); or start a new repository.

Thank.

**Comment by avehtari** [comment]
Great!  I'm fine with using MIT license for PSIS-LOO Julia port. Do you plan to make a separate loo Julia package similar to separate loo R package in CRAN or just include in Stan.jl? Separate loo package was made for R, as it's used by rstan and rstanarm (and possibly by other packages, too).

**Comment by alvaro1101** [comment]
I'm thinking in publishing the code and the demo in a standalone repository or here. Later, maybe trying to merge in Mamba.jl if they accept the pull request or in Stan.jl. In Julia at least Stan.jl and Mamba.jl depends of Mamba.jl itself for diagnose and plotting capabilities and data types.

**Comment by goedman** [comment]
Hi @alvaro1101 ,

Just came back and noticed your message. Let me have a look at your repository and get back to you.

Regards,
Rob

**Comment by alvaro1101** [comment]
Hello @goedman ,

[PSIS.jl](https://github.com/alvaro1101/PSIS.jl) this is the repo. It seems to work, but it needs some checking and cleaning.

Regards.

**Comment by goedman** [comment]
Hi @alvaro1101 ,

It works fine on my machine. 

It's really up to you what you would like to do next. I would suggest to keep it as a separate package (at least for now), complete the checking & cleaning up you mention above, add a short README that points to the publication by Aki/Andrew/Jonah ( https://arxiv.org/pdf/1507.02646v4.pdf ) and choose a name (follow the R practice?) and license model (Aki seems ok with an MIT license) for the package.  

Having it work for both Mamba.jl ( @brian-j-smith , @bdeonovic ) and Stan.jl would be a really nice additional benefit (simcv on line 158 of the demo is already a Mamba.Chains object).

Testing (through runtests.jl in the test directory) will also be simpler with a Mamba.jl test case.

 Let me know if/how I can help.

Regards,
Rob

**Comment by avehtari** [comment]
Note the updated references (I just today remembered to update psis repo)
- Aki Vehtari, Andrew Gelman and Jonah Gabry (2016). Practical Bayesian model evaluation using leave-one-out cross-validation and WAIC. Statistics and Computing, doi:10.1007/s11222-016-9696-4. arXiv preprint arXiv:1507.04544
- Aki Vehtari, Andrew Gelman and Jonah Gabry (2016). Pareto smoothed importance sampling. arXiv preprint arXiv:1507.02646

**Comment by alvaro1101** [comment]
Hi @goedman, @avehtari, 

If @brian-j-smith or @bdeonovic wants to integrate it in Mamba.jl as another diagnosis tool so Stan.jl can benefit from it (previously, I'll adapt it to work with chains too)  I'm OK with that. If not, a standalone package is it.

First I'm going to open a issue with all the changes that the package needs in a check list: Licensing, references, change of name, etc...

I really need help writing the `LICENSE.md`, I don't know nothing about licensing, I don't know how to write down the change in the licensing, how @avehtari permits this change... Beside, I'm not a English native speaker as you can see.

About the name, I'm open to suggestions: Loo.jl, Psis.jl...

The example `demo_wells.jl` is a bit of overkill as a test. Maybe a toy model or generate a sample of fake data?

**Comment by goedman** [comment]
Hi @alvaro1101 ,

Don't worry too much about the LICENSE.md. In fact given that Aki is ok with an MIT license (see his email from 2 days ago), you can just copy Stan's license and update the package name.

My suggestion was not to integrate it in Mamba.jl but make your package work for both Stan.jl and Mamba.jl. As with Rstan and Rstanarm others might develop additional packages using the functionality provided by your package.

Regards,
Rob

**Comment by alvaro1101** [comment]
Hi @goedman ,
I temporarily left the name, just for now. I adapt the package to work with Mamba.jl and Stan.jl and I try to write a test case.

I think that's all.

Regards.
