### ISSUE TITLE
Question regarding K-fold on hierarchical model

### ISSUE THREAD

**Issue by vincentvalton** [avehtari/PSIS#4]
Hi,

I'm trying to use K-fold crossvalidation for a hierarchical model where each subject has a subject-level parameter (theta[i]), that comes from a group-level parameter (theta_group ~ Normal). 
Each subject has 100+ observations, and the likelihood for each subject is the sum of likelihood at each observation given the parameter theta[i] of the subject.

I am running 10-fold crossvalidation by excluding 10% subjects from the training data set in each fold.

However when trying to estimate the fit of the model in the testing dataset (that is, on the 10% of subjects that were excluded from the training dataset -- cvitst), what parameters should I use to calculate the likelihood of each subject in this testing dataset ? I can see in the 'demo_stan_arsenic' that we reuse the model parameters sampled in the testing dataset to estimate the likelihood at these points in the testing dataset. However, I'm not sure how that would apply with multiple individual subjects that each have different parameters.

So far I've thought of using the mean parameter of all subjects as the parameter to 'plug-in' in the generated quantities for the likelihood of the testing dataset (cvitst) but not sure this is the right way to do it :-/

Any pointers would be super appreciated :+1: 
Best,

**Comment by avehtari** [comment]
Hi,

It's better to ask these kind of questions in stan-users forum (this is not really an issue for PSIS code)
You can find my answer in https://groups.google.com/forum/#!category-topic/stan-users/general/28Radt2NuvU

Aki
