### ISSUE TITLE
Make the Python package available on PyPI?

### ISSUE THREAD

**Issue by justinbois** [avehtari/PSIS#6]
I was wondering if you would be interested in making the Python package available in PyPI. It would entail making a setup.py file and setting up the appropriate directory structure. Would not be too hard, and I'd be happy to do it myself.

I am confused about the license, though. The license for the repo is GPL, but there is a BSD license in the actual .py file. To make the package, we'd have to split off the .py file into a new repository (probably something like psispy), and I don't know how to proceed with the conflicting licensing.

I think the easiest thing to do would be to make a new repo with a BSD-3 license, still copyrighted by @avehtari and @tsivula (and we can add me if I set up the package and you think it's appropriate).

Please let me know if you would be interested in doing this. I think it would end up having many more users.

**Comment by avehtari** [comment]
Do you think PSIS would be needed as stand-alone package, or would the implementation in ArviZ
https://arviz-devs.github.io/arviz/api.html be sufficient for your purposes? Arviz includes also useful plotting functions for PSIS.

We changed the license of Python to BSD year ago, but forgot the root directory license file. R code is still GPL, as rstan is GPL anyway (although that will eventually change, too)

**Comment by justinbois** [comment]
Ah, I think ArviZ is sufficient. It does not really have excessive dependencies, and does have teh functionality.

That said, I think it would be useful to link to it in the README of this repo, and also in the loo package on CRAN.

If you agree, I'll let you close the issue. Thanks!

**Comment by justinbois** [comment]
....although "loopy" would be a really fun name for a package! :-)

**Comment by avehtari** [comment]
I added info about Arviz (it was released in PyPI couple weeks ago and I only today checked that that release already has loo and psislw) to README

Yes, "loopy" would be fun name :smile:
