### ISSUE TITLE
Python version of LFO-CV?

### ISSUE THREAD

**Issue by mathDR** [avehtari/PSIS#7]
Are there plans for a lfo-cv function?  I would be willing to work on a PR if you aren't already building one.

**Comment by avehtari** [comment]
As Python version of loo is in ArviZ package https://github.com/arviz-devs/arviz, so maybe LFO-CV could go there, too?

**Comment by mathDR** [comment]
👍 That seems very consistent.  I will raise an issue there.

**Comment by avehtari** [comment]
Although if the current ArviZ loo implementation doesn't support refits, then it may be beyond ArviZ and then I'm happy to accept PR for a LFO-CV example in this repository.
